//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 03:58:35 AM EET 
//


package mychatserver.model.chatsession;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the src.mychatserver.model.chatsession package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Msg_QNAME = new QName("", "Msg");
    private final static QName _Bold_QNAME = new QName("", "bold");
    private final static QName _FontStyle_QNAME = new QName("", "fontStyle");
    private final static QName _Body_QNAME = new QName("", "body");
    private final static QName _Italic_QNAME = new QName("", "italic");
    private final static QName _ChatSession_QNAME = new QName("", "ChatSession");
    private final static QName _Underlined_QNAME = new QName("", "underlined");
    private final static QName _From_QNAME = new QName("", "from");
    private final static QName _FontSize_QNAME = new QName("", "fontSize");
    private final static QName _To_QNAME = new QName("", "to");
    private final static QName _Time_QNAME = new QName("", "time");
    private final static QName _TextBackGround_QNAME = new QName("", "textBackGround");
    private final static QName _FontColor_QNAME = new QName("", "fontColor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: src.mychatserver.model.chatsession
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MsgType }
     * 
     */
    public MsgType createMsgType() {
        return new MsgType();
    }

    /**
     * Create an instance of {@link ChatSessionType }
     * 
     */
    public ChatSessionType createChatSessionType() {
        return new ChatSessionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MsgType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Msg")
    public JAXBElement<MsgType> createMsg(MsgType value) {
        return new JAXBElement<MsgType>(_Msg_QNAME, MsgType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bold")
    public JAXBElement<Boolean> createBold(Boolean value) {
        return new JAXBElement<Boolean>(_Bold_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fontStyle")
    public JAXBElement<String> createFontStyle(String value) {
        return new JAXBElement<String>(_FontStyle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "body")
    public JAXBElement<String> createBody(String value) {
        return new JAXBElement<String>(_Body_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "italic")
    public JAXBElement<Boolean> createItalic(Boolean value) {
        return new JAXBElement<Boolean>(_Italic_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChatSessionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChatSession")
    public JAXBElement<ChatSessionType> createChatSession(ChatSessionType value) {
        return new JAXBElement<ChatSessionType>(_ChatSession_QNAME, ChatSessionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "underlined")
    public JAXBElement<Boolean> createUnderlined(Boolean value) {
        return new JAXBElement<Boolean>(_Underlined_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "from")
    public JAXBElement<String> createFrom(String value) {
        return new JAXBElement<String>(_From_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fontSize")
    public JAXBElement<String> createFontSize(String value) {
        return new JAXBElement<String>(_FontSize_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to")
    public JAXBElement<String> createTo(String value) {
        return new JAXBElement<String>(_To_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time")
    public JAXBElement<XMLGregorianCalendar> createTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Time_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "textBackGround")
    public JAXBElement<String> createTextBackGround(String value) {
        return new JAXBElement<String>(_TextBackGround_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fontColor")
    public JAXBElement<String> createFontColor(String value) {
        return new JAXBElement<String>(_FontColor_QNAME, String.class, null, value);
    }

}
